/* Wish Myself Well — show data for the storyboard comic.
   Tone: Game of Thrones ensemble, Friends courtyard, Anne felt-life, Bluey innocence.
   No character is good or evil. Everyone is wishing themselves well. */

const SHOW = {
  title: "Wish Myself Well",
  channel: "2892",
  banner: "Top 500 Entertainment",
  tagline: "Everyone is wishing themselves well. That’s the whole plot.",
  logline:
    "In a world that has accepted AI, tokenized nearly everything, and started living much longer, a 47-year-old scheduling obsessive, an enlightened tuk-tuk driver, a longevity clinician, a prompt-harvesting analyst, two kids with Lens glasses, a laughing guru, and a corrupt eco-ashram all try to be happy — while the camera treats a paper napkin like the fate of the world.",
  definition: {
    enlightenment:
      "Knowing the Self: the witness. Identifying as the witness — beyond thinking, beyond dualism. Any experience is equal to any other: a vision of God equals the pain in this knee.",
    rich: "Having more than you need. None of these things are needed. All of it is a play of name and form.",
    maya: "All imagination. Dualism. Fundamentally the sense of me and mine. Without that, who is here to experience?",
    wish: "All desire is wishing yourself well. Indulgence is the stupid way. Austerity, love, patience, acceptance — the wise way. Both have the same end in view.",
    city: "The city is only as big as the number of connections in it. Which is to say: as big as your heart is open. For an open heart there are no countries. Only one family.",
  },
  rules: [
    "No absolute good or evil. Even a murderer loves their child. Grey only.",
    "Small everyday dramas, filmed as if the universe depended on this one instance — only when a main character is having to focus hard.",
    "Felt experience drives the show the way Anne of Green Gables does. Conform the camera to whoever we are following.",
    "The more ashamed and worthless a character feels, the more driven they are.",
    "Kids have underdeveloped egos. Their innocence is the reminder under me-and-mine.",
    "The enlightened are natural, like babies. They are not impressive.",
    "Mother told us to laugh at this ignorance. We keep forgetting.",
  ],

  lensAxes: [
    { id: "body", label: "Body" },
    { id: "mind", label: "Mind" },
    { id: "feeling", label: "Feeling" },
    { id: "relation", label: "Relation" },
    { id: "work", label: "Work" },
    { id: "influence", label: "Influence" },
    { id: "love", label: "Love" },
    { id: "seva", label: "Seva" },
  ],

  characters: [
    {
      id: "riven",
      name: "Riven Vale",
      age: 47,
      role: "The Seeker / the scheduler / the writer in the ashram",
      image: "images/wmw-riven.png",
      vibe: "Anne’s inner weather + Friends’ rumpled neighbor + a man who color-codes salvation",
      want: "To become someone: spiritually, sexually, monetarily, experientially, societally. To make samadhi permanent. To get ahead in the ashram, the music app, and this very show.",
      wound: "After turning 47 he can hear the words crazy loser in his own mouth. Mother Anu once said it, then said she was kidding, then told the other swamis they should be more like him — meaning innocent. He filed the first sentence. He missed the third.",
      wishStyle: "Stupid way wearing the costume of the wise way: a calendar so complete it could pass for tapas.",
      quote: "Please help me pay this bill. Without you I am nothing but a crazy loser wasting a life.",
      bio: "Lives in The Well, a tokenized courtyard that wants to be a sitcom. Works a private 9-to-5 on proving himself, then fails the assignment his guru actually gave: take care of the body and mind first. Sadness is the trigger — a missed opportunity, a day that did not match the schedule — and then the old blue-light binge, then shame, then more blocks on the calendar. He told Anu he would die if she would not enlighten him that minute. She pretended concern, smiled, pinched his cheek, hugged him. She knew he wouldn’t. Called his bluff. He’d been blessed and he used the blessing as another item to optimize.",
      schedule: [
        { t: "04:47", name: "Witness sit", note: "Usually becomes planning." },
        { t: "05:15", name: "Body", note: "Stretch, walk, the assignment. Often skipped for the schedule of the assignment." },
        { t: "06:00", name: "Color-code Year 47", note: "The chapel." },
        { t: "09:00–17:00", name: "Prove it", note: "Music app. Ashram Slack. Channel 2892. Eminem-hours, without the rest." },
        { t: "17:00", name: "Body again", note: "Rarely." },
        { t: "21:00", name: "Sleep", note: "Does not." },
        { t: "unscheduled", name: "Sadness", note: "Missed opportunity. Then blue light. Then shame. Then more calendar." },
      ],
      lens: { body: 28, mind: 86, feeling: 34, relation: 47, work: 71, influence: 16, love: 68, seva: 52, witness: 64, pain: 74 },
      lensLater: { body: 31, mind: 70, feeling: 48, relation: 55, work: 40, influence: 14, love: 72, seva: 60, witness: 78, pain: 40 },
    },
    {
      id: "anu",
      name: "Mother Anu",
      age: 67,
      role: "The guru who kids",
      image: "images/wmw-anu.png",
      vibe: "Bluey’s mum if she were also the weather",
      want: "That they take care of the body and mind first. Use whatever method. Then help. One unhappy person helping another is just two unhappy people.",
      wound: "She feels everyone’s sadness on the road to a house visit. Staff of a hundred still cannot finish the mail.",
      wishStyle: "Wise. Also: pinch, hug, joke, refuse to be recruited into their emergency.",
      quote: "Crazy loser. I’m kidding. You should be more like him.",
      bio: "She called Riven a crazy loser, then said she was kidding, then told the order’s swamis to imitate his innocence. All three sentences were true. She will not make anyone enlightened on a timetable. She will not be threatened into it. She laughs at ignorance and keeps being forgotten.",
      lens: { body: 55, mind: 40, feeling: 88, relation: 95, work: 90, influence: 80, love: 99, seva: 99, witness: 97, pain: 8 },
      lensLater: { body: 55, mind: 38, feeling: 90, relation: 95, work: 88, influence: 80, love: 99, seva: 99, witness: 97, pain: 8 },
    },
    {
      id: "biju",
      name: "Biju",
      age: 54,
      role: "Enlightened tuk-tuk driver",
      image: "images/wmw-biju.png",
      vibe: "The Matrix filmed as a man handing you a napkin",
      want: "Nothing that would survive being said out loud.",
      wound: "A knee. Equal to God in a puddle.",
      wishStyle: "None. Or: whatever is, is a gift.",
      quote: "—",
      bio: "Almost none of the action should be a shootout. Biju is the shootout. Rain, tokens crashing on a passenger’s screen, a paper napkin offered with both hands. The camera circles as if cities were falling. He is ordinary. He laughs like a child. A cat walks by.",
      lens: { body: 42, mind: 22, feeling: 70, relation: 60, work: 35, influence: 4, love: 90, seva: 80, witness: 98, pain: 12 },
      lensLater: { body: 40, mind: 20, feeling: 72, relation: 60, work: 35, influence: 4, love: 90, seva: 80, witness: 98, pain: 12 },
    },
    {
      id: "mira",
      name: "Mira Chen",
      age: 32,
      role: "Longevity clinician at The Well",
      image: "images/wmw-mira.png",
      vibe: "Friends’ Monica, if the apartment were a clinic for not dying",
      want: "To live long enough to be loved for real. To be wanted. To never fold.",
      wound: "She can keep a cell young with a few gene-switches. She cannot switch off the hunger in the eyes of a 140-year-old who looks 35.",
      wishStyle: "Stupid way, medical: a circumstance (more years) will make me happy.",
      quote: "Drink this. You’ll have time.",
      bio: "People inject, or drink, their health. Factions of youth believe we can live forever. Mira sells the vial and wants the vial. She is kind. She is selling time to people who will use it to remain themselves.",
      lens: { body: 88, mind: 70, feeling: 38, relation: 50, work: 80, influence: 44, love: 36, seva: 25, witness: 18, pain: 55 },
      lensLater: { body: 80, mind: 62, feeling: 44, relation: 58, work: 70, influence: 40, love: 48, seva: 30, witness: 28, pain: 42 },
    },
    {
      id: "oren",
      name: "Oren Kade",
      age: 41,
      role: "Prompt Bureau / Lens analyst",
      image: "images/wmw-oren.png",
      vibe: "A spy plot that would rather be a social worker",
      want: "To map the human being well enough to help. Or to sell. Or to steer. He has not admitted which employer he actually has.",
      wound: "Kind face, unkind dashboards. AI prompts are the floodgate. Getting clean signal on a person, a clique, a nation — still hard.",
      wishStyle: "Control as care.",
      quote: "Intervention or product?",
      bio: "Wears the Lens. Sees pain-bodies as weather. Flags Riven’s shame spike at 4:47. His boss says both. Governments, ranking stark now that money decentralized, buy the same flowers of data the shops buy.",
      lens: { body: 60, mind: 82, feeling: 40, relation: 44, work: 85, influence: 62, love: 35, seva: 30, witness: 22, pain: 48 },
      lensLater: { body: 58, mind: 75, feeling: 50, relation: 52, work: 70, influence: 55, love: 42, seva: 40, witness: 35, pain: 36 },
    },
    {
      id: "lumen",
      name: "Lumen",
      age: 38,
      role: "Pain-body cartographer",
      image: "images/wmw-lumen.png",
      vibe: "The person who can see the 4D chart and still forgets to eat",
      want: "To understand what a human being is. To make the chart honest.",
      wound: "The Lens shows everything except the witness. The witness does not plot.",
      wishStyle: "Knowledge as safety.",
      quote: "The pain-body is not you. It just got used to being called that.",
      bio: "Studies Tolle’s pain-body as a visible weather system in the Lens. Works among orgs that want evolution, sales, or control. Lives at The Well. Sunday sofa. Explains the chart to kids who already see it.",
      lens: { body: 48, mind: 90, feeling: 55, relation: 40, work: 77, influence: 28, love: 42, seva: 35, witness: 58, pain: 33 },
      lensLater: { body: 52, mind: 80, feeling: 62, relation: 55, work: 60, influence: 24, love: 55, seva: 48, witness: 70, pain: 22 },
    },
    {
      id: "kids",
      name: "Juniper & Moss",
      age: "9 and 6",
      role: "Underdeveloped egos",
      image: "images/wmw-kids.png",
      vibe: "Bluey, without the cartoon — the reason adults remember",
      want: "A wet stone. To make the glasses show Mommy as a cloud pretending to be a house.",
      wound: "None that have hardened into story. Yet.",
      wishStyle: "Play. The original wise way, before it learned its name.",
      quote: "Uncle Riven is a lantern made of hours.",
      bio: "Cal’s kids. They put on the Lens as a game. They see metrics without deciding what they mean. Innocence makes the courtyard laugh and love. The show returns to them the way a breath returns.",
      lens: { body: 80, mind: 30, feeling: 85, relation: 90, work: 5, influence: 2, love: 95, seva: 40, witness: 82, pain: 6 },
      lensLater: { body: 80, mind: 32, feeling: 80, relation: 90, work: 5, influence: 2, love: 95, seva: 45, witness: 80, pain: 8 },
    },
    {
      id: "puck",
      name: "Puck Reed",
      age: 36,
      role: "The roommate whose life works",
      image: "images/wmw-puck.png",
      vibe: "Friends’ Joey, if Joey had a dog and no prayer",
      want: "Not much. That’s the insult.",
      wound: "He is glad when Riven’s worldly boons miss. No enlightened person, he says, was a rock star first.",
      wishStyle: "Feet on the table. Bad dog. Sit. Same mechanics, less begging.",
      quote: "I’m glad you didn’t get it. Stay hungry. Stay nobody.",
      bio: "Cut from Riven on his knees at the lamp: Puck in the courtyard with Jack the mutt, kicking his feet up, having the same or more success. It is not spiritual. It is the structures of the world. Riven cannot stand it and loves him.",
      lens: { body: 70, mind: 35, feeling: 62, relation: 70, work: 55, influence: 40, love: 50, seva: 15, witness: 12, pain: 20 },
      lensLater: { body: 68, mind: 35, feeling: 60, relation: 72, work: 55, influence: 40, love: 52, seva: 18, witness: 14, pain: 18 },
    },
    {
      id: "tess",
      name: "Tess Morrow",
      age: 41,
      role: "No-AI compound / team ego with dirt under the nails",
      image: "images/wmw-tess.png",
      vibe: "A GoT banner that grows tomatoes",
      want: "Her people safe. Kids touching dirt. The old world not eaten.",
      wound: "She believes something is threatened. The rifle is unloved and loaded.",
      wishStyle: "Me and mine as good, other as threat. Wishing the team well.",
      quote: "We are not a cult. We are a garden that can hear.",
      bio: "Back-to-natural, no AI adoption. Conspiracy is a vast array now, believed by more and more. Some armed. Tess is not a villain. She is a mother whose heart-city has walls.",
      lens: { body: 75, mind: 55, feeling: 48, relation: 80, work: 60, influence: 30, love: 70, seva: 50, witness: 15, pain: 58 },
      lensLater: { body: 75, mind: 50, feeling: 52, relation: 82, work: 58, influence: 28, love: 74, seva: 55, witness: 22, pain: 50 },
    },
    {
      id: "sol",
      name: "Father Sol",
      age: 53,
      role: "Lecherous “enlightened” teacher of the Tamera hill",
      image: "images/wmw-sol.png",
      vibe: "GoT priest, free-love marketing, a mouth that says oneness",
      want: "To be adored as the door. To keep the seniors complicit.",
      wound: "He may have touched something real twenty years ago. The me-and-mine of being the one who touched it ate the rest.",
      wishStyle: "Stupid way in sacred language. Sex as curriculum.",
      quote: "Awareness and matter are one. So are we.",
      bio: "Corrupted senior devotees, new batch of students, and Ilya who weeps with joy just to stand near him. What will happen this week. The show does not make him a devil. It makes him a man wishing himself well with other people’s bodies.",
      lens: { body: 82, mind: 75, feeling: 30, relation: 88, work: 70, influence: 85, love: 20, seva: 18, witness: 8, pain: 62 },
      lensLater: { body: 80, mind: 70, feeling: 22, relation: 70, work: 65, influence: 80, love: 15, seva: 10, witness: 6, pain: 75 },
    },
    {
      id: "ilya",
      name: "Ilya",
      age: 22,
      role: "The incorruptible youth (this week)",
      image: "images/wmw-ilya.png",
      vibe: "Anne’s wonder, aimed at the wrong sun",
      want: "To stay in the Swami’s presence. To not waste the tears.",
      wound: "Devotion is real. The object may not deserve it. Reality does not always coordinate those two facts.",
      wishStyle: "Love. The wise way pointed at a person.",
      quote: "I shed tears of ecstatic joy. That part isn’t fake.",
      bio: "New student on Father Sol’s hill. The camera loves him because the courtyard loves kids, and he is still partly a kid. The seniors watch to see when the innocence will be useful.",
      lens: { body: 70, mind: 40, feeling: 92, relation: 60, work: 20, influence: 5, love: 90, seva: 70, witness: 45, pain: 15 },
      lensLater: { body: 65, mind: 50, feeling: 60, relation: 40, work: 25, influence: 8, love: 55, seva: 50, witness: 40, pain: 48 },
    },
    {
      id: "harsha",
      name: "Swami Harsha",
      age: 72,
      role: "The heckler-saint",
      image: "images/wmw-harsha.png",
      vibe: "Stand-up that sits down into silence",
      want: "That they laugh. Then that they shut up.",
      wound: "None he will confess. He answers with your-momma jokes, then the room is a lake.",
      wishStyle: "Laugh at ignorance. Clap. Forget pride.",
      quote: "Mother told us to laugh. We made it a practice instead of a laugh.",
      bio: "Visiting teacher. Filthy, precise, then still. A swami in the same order who was told to be more like Riven and does not know whether to be insulted. He can moo the essence of Aum until grown men have to moo back. Cows are moving pieces of hill.",
      lens: { body: 50, mind: 30, feeling: 80, relation: 70, work: 40, influence: 55, love: 85, seva: 70, witness: 94, pain: 5 },
      lensLater: { body: 50, mind: 28, feeling: 82, relation: 70, work: 40, influence: 55, love: 85, seva: 70, witness: 94, pain: 5 },
    },
    {
      id: "vale",
      name: "The Vales",
      age: "family",
      role: "Responsibility, knowledge, balance",
      image: "images/wmw-panel-07.png",
      vibe: "Bluey kitchen under adult weather",
      want: "Pike: that the lights stay on. Sera: that they understand. Cal: that no one has to be a project.",
      wound: "Their seeker is run more ragged than any of them. They love him and cannot schedule him into rest.",
      wishStyle: "Ordinary love. The most advanced, least branded.",
      quote: "Sit. The food is already hot.",
      bio: "Pike does responsibility. Sera does knowledge, wisdom. Cal does balance — the smart one, not seeking, just living. Sunday dinner is the Friends table that happens to be blood. Riven arrives late with the calendar still on his phone.",
      lens: { body: 62, mind: 70, feeling: 65, relation: 84, work: 70, influence: 20, love: 80, seva: 45, witness: 30, pain: 25 },
      lensLater: { body: 62, mind: 68, feeling: 70, relation: 88, work: 68, influence: 20, love: 84, seva: 48, witness: 35, pain: 20 },
    },
  ],

  episode1: {
    id: "e01",
    code: "2892.01",
    title: "Crazy Loser (kidding)",
    logline:
      "A napkin in the rain; a 47-year-old chapel of calendars; a guru who names him and unnames him in one breath; kids who see the cage; a vial of years; a dashboard of shame; a kitchen; a prayer versus a dog; a knee equal to God.",
    note: "Prestige-TV stills. Ordinary stakes. Matrix camera only when a character we follow has to focus.",
    panels: [
      {
        n: 1,
        slug: "EXT. RAIN CITY / BIJU’S TUK-TUK — DUSK",
        camera:
          "Bullet-time on a paper napkin. Water hangs. Treat the handoff like the last wire on a bomb. No music swell until the passenger actually takes it.",
        image: "images/wmw-panel-01.png",
        felt: "The passenger’s wallet-token has crashed. The feeling is: I will not exist if the number is wrong. Biju feels the knee, the rain, the crying, equally. He does not help the number. He helps the hand.",
        lines: [
          { who: "Passenger", text: "It’s gone. It’s — I had a year in there." },
          { who: "Biju", text: "…" },
          { who: "Passenger", text: "Say something." },
          { who: "Biju", text: "Wipe your face." },
        ],
      },
      {
        n: 2,
        slug: "INT. THE WELL / RIVEN’S ROOM — 04:47",
        camera:
          "Slow push on stacked calendar light. He is the monk and the prison architect. Hold on the boy in the 47-year-old face.",
        image: "images/wmw-panel-02.png",
        felt: "Year 47. The body has not been taken care of. The mind is a cathedral of blocks. If the schedule is perfect, the loser cannot be real. If the loser is real, the schedule will save him. Both thoughts are the same thought.",
        lines: [
          { who: "Riven (aloud, to the blocks)", text: "Body first. Then mind. Then the app. Then Slack. Then sleep." },
          { who: "Riven (smaller)", text: "I can do 9 to 5. I can be like him. Work, then rest." },
          { who: "The calendar", text: "You did not rest yesterday either." },
        ],
      },
      {
        n: 3,
        slug: "FLASHBACK — ASHRAM COURTYARD / AFTERNOON",
        camera:
          "Close as a love scene on the pinch. She is laughing. He is dying and being born. Swamis in the dust behind, hearing a different sentence.",
        image: "images/wmw-panel-03.png",
        felt: "He had said: make me enlightened or I will not stay in this body. She pretended to look concerned. Then the smile. Then the cheek. Then the hug. Later, in front of others: crazy loser. I’m kidding. You should be more like him. Innocent. He took crazy loser home and scheduled it.",
        lines: [
          { who: "Riven", text: "If you won’t do it now I don’t — I can’t —" },
          { who: "Anu", text: "Crazy loser." },
          { who: "Anu", text: "I’m kidding." },
          { who: "Anu (to the swamis)", text: "You should be more like him." },
        ],
      },
      {
        n: 4,
        slug: "EXT. THE WELL COURTYARD — GOLDEN HOUR",
        camera:
          "From the kids’ Lens: Riven as a gold cage of hours. Wonder, not horror. Bluey-bright. Then cut to his face, which does not know it is a lantern.",
        image: "images/wmw-panel-04.png",
        felt: "Juniper and Moss have underdeveloped egos. They have not yet mistaken the feeling of becoming someone for a self. They see Uncle Riven and tell the truth without cruelty.",
        lines: [
          { who: "Moss", text: "He’s a house made of lists." },
          { who: "Juniper", text: "No. A lantern made of hours. See? He’s lit. He’s just on the inside of it." },
          { who: "Moss", text: "Can we let him out?" },
          { who: "Juniper", text: "He has to put the glasses on. He thinks the glasses are the schedule." },
        ],
      },
      {
        n: 5,
        slug: "INT. MIRA’S CLINIC — DAY",
        camera:
          "Clinical beauty. Hold on the empty of the man who looks 35. The vial is the wish: this object, this year, this cell that will not fold.",
        image: "images/wmw-panel-05.png",
        felt: "Fewer switches now, to keep a cell young. A city of folding proteins, each with a job. Mira wants him to want her as much as he wants the liquid. He wants time. Neither of them wants the knee, or the puddle.",
        lines: [
          { who: "Patient", text: "Will I still be me." },
          { who: "Mira", text: "That’s the product." },
          { who: "Patient", text: "Good." },
        ],
      },
      {
        n: 6,
        slug: "INT. PROMPT BUREAU — NIGHT",
        camera:
          "Dashboard as scrying bowl. Pain-body weather over a 4D flower. Two faces in the glass: care, and inventory.",
        image: "images/wmw-panel-06.png",
        felt: "The prompts people write to AI are the floodgate. Riven’s 4:47 shame is a spike. Oren feels a flicker of actual concern and files it under both.",
        lines: [
          { who: "Oren", text: "Shame spike. Seeker cluster. He thinks he’s a person who failed a morning." },
          { who: "Boss", text: "Intervention or product?" },
          { who: "Oren", text: "…" },
          { who: "Boss", text: "Both is a number we can sell." },
        ],
      },
      {
        n: 7,
        slug: "INT. VALE KITCHEN — SUNDAY",
        camera:
          "Sitcom coverage, then one extra-long take on the father’s hands passing a dish. Fate-of-the-world seriousness on steam.",
        image: "images/wmw-panel-07.png",
        felt: "Pike does responsibility. Sera does knowledge. Cal does balance. Riven does the seeker, run more ragged than any of them, late, apologizing with a plan for how he will not be late.",
        lines: [
          { who: "Pike", text: "Sit. The food is already hot." },
          { who: "Riven", text: "I can do 9 to 5 starting tomorrow. Body first. I wrote it in ink." },
          { who: "Cal", text: "Eat." },
          { who: "Sera", text: "He heard loser again. You can see it in the shoulders." },
        ],
      },
      {
        n: 8,
        slug: "INT./EXT. THE WELL — NIGHT, SAME HOUR",
        camera:
          "Split: Riven on his knees at the lamp. Through the door, Puck and the dog, feet up. No moral. Two mechanics.",
        image: "images/wmw-panel-09.png",
        felt: "Please help me pay this bill. Without you I am nothing but a crazy loser wasting a life. Across the courtyard: Bad dog. Sit. The same world answers both men. Riven cannot stand that this is true.",
        lines: [
          { who: "Riven", text: "Please. The bill. I won’t waste it. I’ll take care of the body. I’ll—" },
          { who: "Puck (off, to the dog)", text: "Bad dog. Sit." },
          { who: "Puck (to Riven, later, kind)", text: "I’m glad the app didn’t close. Stay nobody a little longer." },
        ],
      },
      {
        n: 9,
        slug: "INT. FARID & YASMIN’S ROOMS — DUSK",
        camera:
          "Do not editorialize. He washes her feet. A drone hunts a headline. Grey. Let Western eyes get uncomfortable without being handed a verdict.",
        image: "images/wmw-panel-10.png",
        felt: "Some countries call this illegal the other direction. Some traditions, seen on a different angle, are waiting on her hand and foot: not a sex object, a soul. The drone wants a villain. The show refuses.",
        lines: [
          { who: "Drone feed (text overlay)", text: "OPPRESSION — LIVE" },
          { who: "Farid", text: "Does it hurt." },
          { who: "Yasmin", text: "The watching does." },
        ],
      },
      {
        n: 10,
        slug: "EXT. PUDDLE / EMPTY TUK-TUK — NIGHT",
        camera:
          "Circle as if cities were ending. Knee. Then God in the water. Equal. Child-laugh. Cat. Hold long after the joke of it lands.",
        image: "images/wmw-panel-08.png",
        felt: "Life could stop. He has been rich the whole time. Rich = having more than you need. None of this is needed. Name and form. The seeker, across town, is still building Year 47. Both are the play. Mother told us to laugh.",
        lines: [
          { who: "Biju (to the knee, to the puddle)", text: "—" },
          { who: "A cat", text: "—" },
          { who: "Channel 2892 (end card)", text: "WISH MYSELF WELL" },
        ],
      },
    ],
  },

  world: {
    time: "A little after the dollar stopped being the default stored value. Tokens are ordinary. AI is accepted. Robots are furniture. The moon is a commute for work crews; the nearest planet is a rich person’s weekend. Trash-eating, plastic-eating, oil-eating bacteria took the edge off the old inhabitable-earth panic. Iron can be spun from pollutants in the air. The biggest breakthrough is not that. The biggest breakthrough is inside, and it has the ratings.",
    money: "Decentralized stored value is the standard. Alt-coins already run AI agents. Governments still rank — maybe starker, maybe not. Tax teams, law teams, emotional-upholding teams, mental-upholding teams all still wish their team well.",
    body: "2006: many switches, a cell can become stem. Later: fewer switches to keep a cell young. People inject or drink their health. Factions of youth, and people who would control them, believe we can live forever.",
    lens: "Subtle VR contacts and glasses. A 3D / 4D / more-D chart of a person: body, mind, feeling, relation, work, influence, love, seva — and time. Pain-body as weather. The witness does not plot. Orgs use it to help, to sell, to steer. Prompts to AI are the floodgate they all need and cannot quite clean.",
    entertainment:
      "Channel 2892. Top 500. Micro-camera movies are illegal; this still leaked to Beast-scale because the inner life is the hit. Some worship AI, since awareness and matter can be read as God and creation. The writer of this show is in the ashram, using AI, written into the series.",
    cityHeart:
      "The city is only as big as your connections. As big as the heart is open. No countries for an open heart. One family.",
  },

  seeds: [
    {
      title: "Channel 2892",
      bag: "Meta",
      text: "The most popular entertainment is the inner breakthrough. Micro-cameras illegal; the show is too good. Riven is in the ashram writing it with AI. The writer is a character.",
    },
    {
      title: "Father Sol’s week",
      bag: "Ashram grey",
      text: "Lecherous “enlightened” teacher, corrupted seniors, Ilya’s real tears. What happens this week. No devil. A man wishing himself well with other people’s bodies.",
    },
    {
      title: "Attraction Catch-22",
      bag: "Sofa",
      text: "Once the mind is pure enough that people see themselves in you, you no longer want the freaky fun. Only what’s best for society. A bum deal, man. Fallen yogis? Supposedly.",
    },
    {
      title: "Almost-boons",
      bag: "Riven / Puck",
      text: "Riven almost gets the app, the money, the ashram rank, the girl. Puck is glad. No enlightened person was a rock star first.",
    },
    {
      title: "Your momma, then the lake",
      bag: "Harsha",
      text: "Heckler. Filthy joke. Room becomes silence. Superpower is not being nice. It is being earnest to realize the Self.",
    },
    {
      title: "Moo",
      bag: "Harsha",
      text: "A swami moos the essence of Aum. Everyone has to moo back. Cows are of the earth. Moving pieces of hill. Nature teaches sacrifice.",
    },
    {
      title: "The lamp goes out",
      bag: "Comic holy",
      text: "Someone worships the lamp, open-eye meditation. A goof blows it out. The scene is stupid and then not.",
    },
    {
      title: "Bicycle monks",
      bag: "Kids",
      text: "Camp in the tree house to run away with bicycle monks. One older monk: this one has had his own realization. He’ll come on his own. Give him time.",
    },
    {
      title: "Highlander of tendencies",
      bag: "Inner action",
      text: "Lower tendencies as shadows of virtues; then the virtues themselves; then the guru who does not resist. There can be only one. Then silence on the throne. A dying warrior: though my face is writhing, I am in bliss.",
    },
    {
      title: "Sword without blinking",
      bag: "Grey duel",
      text: "Do you know who I am? I could run this sword through you without blinking. Do you know who I am? I could let you. Velvet revolution: evolution, not 60s revolution.",
    },
    {
      title: "The chain that wasn’t",
      bag: "Lens parable",
      text: "A girl walks all day as if a new chain made her beautiful. Colleagues include her. Mother praises her. The chain was never on. Confidence was. The Lens would have shown the chart move with no object.",
    },
    {
      title: "Lawyer at home, judge abroad",
      bag: "Team ego",
      text: "We defend our own mistakes and sentence other people’s. Focusing on another’s fault brings that fault out in us, sometimes stronger. Seva is the way out that actually works.",
    },
    {
      title: "Serving Strange Gods",
      bag: "Title in the world",
      text: "Band name and episode title. AI worshippers. Token cults. Gene-switch churches. All grey.",
    },
    {
      title: "Open-heart map",
      bag: "World",
      text: "Aerial of the city: only connections exist. Slide the heart open: countries dissolve. Tess’s compound is a bright knot with a wall. Biju’s city is large and poor and enough.",
    },
    {
      title: "Samadhi is a state",
      bag: "Anu / Riven",
      text: "Are you always in samadhi? Of course not. I am beyond samadhi. You have all the realization you need. You do not trust it. The whole idea of self-realization is a mistake.",
    },
    {
      title: "Screen",
      bag: "Bible line",
      text: "I am like a cinema screen. Pictures pass. Destiny is of the people on the screen. Not mine.",
    },
    {
      title: "Aliens in the host",
      bag: "Freak occurrence",
      text: "Some can inhabit bodies. A small group of them are self-realized; through company the host becomes so. The narrator is one. Used sparingly. The boring day remains the engine.",
    },
    {
      title: "G Block",
      bag: "Ashram comic",
      text: "D Block or G Block? She traces a letter that does not look like a G.",
    },
    {
      title: "Happiness is a decision",
      bag: "Anu",
      text: "If they knew how much trouble their sadness caused her, they would try harder to choose it. Still: no morals higher or lower. Just the chart moving.",
    },
    {
      title: "Take care of the tools",
      bag: "North star",
      text: "Body and mind are the only vehicles across the ocean. Stray a little and you lose yourself in the dream. Use whatever method. First, the tools.",
    },
  ],
};
